/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestCoppeliaCST;

import co.nstant.in.cbor.CborException;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws CborException, IOException {
        Environment env = new Environment();
        env.startSimulation();
        System.out.println(env.getAgentPosition());
        System.out.println(env.getApplesInVision());
        env.stopSimulation();
    }
}
